# Generated by Django 6.1 on 2026-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('team', 'key')},
        ),
    ]
