# Generated by Django 6.1 on 2026-09-09 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('redis_stream', 'Redis Stream'), ('email', 'Email')], max_length=32)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['delivered_at', 'created_at'], name='outbox_outb_deliver_e6819e_idx')],
            },
        ),
    ]
