# Generated by Django 6.1 on 2026-08-31 12:21

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0004_ticket_story_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('body', models.TextField()),
                ('attachment_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list)),
                ('mentioned_user_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='comments_ticket__68f46a_idx')],
            },
        ),
    ]
