# Generated by Django 6.1 on 2026-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='story_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
