# Generated by Django 6.1 on 2026-09-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_story_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
